FROM python:3.7.4-alpine3.10

RUN apk --no-cache add ca-certificates git py3-pip

RUN git clone https://github.com/s0md3v/Corsy.git
WORKDIR /Corsy
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

ENTRYPOINT ["python3", "corsy.py"]